apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  database_url: mongodb-service
# external configuration
#centralised 
#share with other components 
# also needign to be created before the actual deployment.yaml apply